# Generated by Django 4.2.2 on 2023-06-22 14:05

import Models.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carrito',
                'db_table': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categoria',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_role', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Role',
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='Type_prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=50)),
                ('dimensions', models.CharField(max_length=20)),
                ('guarantee', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo_producto',
                'verbose_name_plural': 'Tipo_producto',
                'db_table': 'Type_prod',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=50)),
                ('reference', models.BigIntegerField()),
                ('description', models.TextField()),
                ('name_provider', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('initial_price', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=True)),
                ('p_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.category')),
                ('type_Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.type_prod')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Producto',
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('type_doc', models.CharField(max_length=4)),
                ('document', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('adress', models.CharField(max_length=60)),
                ('p_Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.role')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Persona',
                'db_table': 'People',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(Models.models.OrderStatus['CREATED'], 'CREATED'), (Models.models.OrderStatus['PAYED'], 'PAYED'), (Models.models.OrderStatus['COMPLETED'], 'COMPLETED'), (Models.models.OrderStatus['CANCELED'], 'CANCELED')], default='CREATED', max_length=50)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('o_People', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.people')),
            ],
            options={
                'verbose_name': 'Orden_compra',
                'verbose_name_plural': 'Ordene_compra',
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Detail_sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sale', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.PositiveIntegerField()),
                ('total_price', models.PositiveIntegerField()),
                ('ds_Carts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.carts')),
            ],
            options={
                'verbose_name': 'Detalle_venta',
                'verbose_name_plural': 'Detalle_venta',
                'db_table': 'Detail_sale',
            },
        ),
        migrations.AddField(
            model_name='carts',
            name='c_People',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Models.people'),
        ),
        migrations.AddField(
            model_name='carts',
            name='c_Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Models.product'),
        ),
    ]
