# Generated by Django 4.1.7 on 2023-07-13 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=500)),
                ('reference', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('groups', models.ManyToManyField(blank=True, to='auth.group', verbose_name='Grupos')),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_name', models.CharField(max_length=30)),
                ('document', models.IntegerField()),
                ('date_birth', models.DateField()),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('fk_id_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('user_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.role')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'user',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='TypeProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('fk_id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.category')),
            ],
            options={
                'db_table': 'type_prod',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sale', models.DateField()),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fk_id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.product')),
            ],
            options={
                'db_table': 'sale',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='fk_id_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.status'),
        ),
        migrations.AddField(
            model_name='product',
            name='fk_id_type_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.typeprod'),
        ),
        migrations.CreateModel(
            name='DetailSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fk_id_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.sale')),
            ],
            options={
                'db_table': 'detail_sale',
            },
        ),
        migrations.CreateModel(
            name='DetailProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField()),
                ('color', models.CharField(max_length=30)),
                ('size_p', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=40)),
                ('quantity', models.IntegerField()),
                ('fk_id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.product')),
            ],
            options={
                'db_table': 'detail_prod',
            },
        ),
    ]
