# Generated by Django 4.2.2 on 2023-06-22 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='p_Category',
        ),
        migrations.AddField(
            model_name='type_prod',
            name='p_Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Models.category'),
            preserve_default=False,
        ),
    ]
