# Generated by Django 4.1.7 on 2023-08-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailprods',
            name='quantity',
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
