# Generated by Django 4.1.7 on 2023-06-30 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='type_doc',
        ),
    ]
