# Generated by Django 4.1.7 on 2023-08-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_remove_detailprods_quantity_products_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
