# Generated by Django 4.1.7 on 2023-06-30 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_remove_people_type_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='adress',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='document',
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='last_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='phone',
            field=models.PositiveBigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000000000, message='el número debe tener mínimo 10 digitos'), django.core.validators.MaxValueValidator(9999999999, message='el número debe tener máximo 10 digitos')]),
        ),
        migrations.AlterField(
            model_name='people',
            name='status',
            field=models.BooleanField(default=True, unique=True),
        ),
    ]
