# Generated by Django 4.1.7 on 2023-08-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_alter_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='groups',
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
