# Generated by Django 4.1.7 on 2023-07-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_alter_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='Status_g',
        ),
    ]
