# Generated by Django 4.1.7 on 2023-07-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0003_rename_status_status_g'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fk_id_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Models.category'),
            preserve_default=False,
        ),
    ]
