# Generated by Django 4.1.7 on 2023-07-25 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0004_product_fk_id_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fk_id_category',
        ),
    ]
