# Generated by Django 4.1.7 on 2023-06-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0006_alter_people_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
